Create/delete posts
VangSang0/SkillSwap pull request #10
Opened 2024-04-23 21:48 UTC by VangSang0

Creating and deleting posts:

- app.py has some functionalities
- some html as well on the homepage
- created a few new html's as well

Please check every one of those out

2024-04-24 03:32 UTC, linalu12 requested changes
only left one possible change under the add post method, I think you should add something regarding if the content of the post is empty

2024-04-24 03:32 UTC, linalu12 commented on app.py
> +    for post in all_posts:
randomizing posts and user in session look good!

2024-04-24 03:32 UTC, linalu12 commented on app.py
> +    if post_id is None:
perhaps add  " and if post-content is None"  in test case

2024-04-24 03:32 UTC, linalu12 commented on app.py
> +
lgtm!

2024-04-24 03:32 UTC, linalu12 commented on app.py
> +    database_methods.delete_post(post_id)
lgtm

2024-04-24 03:32 UTC, linalu12 commented on app.py
> +
everything looks great Sang!

2024-04-24 03:32 UTC, linalu12 commented on repositories/database_methods.py
> +            # what can I return here?
queries lgtm

2024-04-24 03:32 UTC, linalu12 commented on static/script.js
> +
nice event listeners for post edit

2024-04-25 01:54 UTC, dali-t commented
lgtm!

2024-04-25 20:04 UTC, merged